# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ServerGui(object):
    def setupUi(self, ServerGui):
        ServerGui.setObjectName("ServerGui")
        ServerGui.resize(800, 600)
        ServerGui.setMinimumSize(QtCore.QSize(800, 600))
        ServerGui.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(ServerGui)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 559))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 4)
        self.statisticLab = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(16)
        self.statisticLab.setFont(font)
        self.statisticLab.setObjectName("statisticLab")
        self.gridLayout.addWidget(self.statisticLab, 4, 1, 1, 1)
        self.clientsList = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.clientsList.setObjectName("clientsList")
        self.gridLayout.addWidget(self.clientsList, 5, 0, 1, 1)
        self.serverSettingsLab = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(16)
        self.serverSettingsLab.setFont(font)
        self.serverSettingsLab.setObjectName("serverSettingsLab")
        self.gridLayout.addWidget(self.serverSettingsLab, 0, 0, 1, 2)
        self.staticticTable = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.staticticTable.setToolTip("")
        self.staticticTable.setToolTipDuration(8)
        self.staticticTable.setWhatsThis("")
        self.staticticTable.setAutoFillBackground(True)
        self.staticticTable.setObjectName("staticticTable")
        self.staticticTable.setColumnCount(0)
        self.staticticTable.setRowCount(0)
        self.gridLayout.addWidget(self.staticticTable, 5, 1, 1, 3)
        self.ipLab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ipLab.setObjectName("ipLab")
        self.gridLayout.addWidget(self.ipLab, 1, 0, 1, 1)
        self.ipLE = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ipLE.setToolTip("")
        self.ipLE.setStatusTip("")
        self.ipLE.setWhatsThis("")
        self.ipLE.setPlaceholderText("")
        self.ipLE.setObjectName("ipLE")
        self.gridLayout.addWidget(self.ipLE, 1, 1, 1, 1)
        self.portSpin = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.portSpin.setObjectName("portSpin")
        self.gridLayout.addWidget(self.portSpin, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.portLab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.portLab.setObjectName("portLab")
        self.gridLayout.addWidget(self.portLab, 2, 0, 1, 1)
        self.clientListLab = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(16)
        self.clientListLab.setFont(font)
        self.clientListLab.setObjectName("clientListLab")
        self.gridLayout.addWidget(self.clientListLab, 4, 0, 1, 1)
        self.btn_quit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_quit.setObjectName("btn_quit")
        self.gridLayout.addWidget(self.btn_quit, 6, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setColumnStretch(3, 2)
        ServerGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ServerGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        ServerGui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ServerGui)
        self.statusbar.setObjectName("statusbar")
        ServerGui.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(ServerGui)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ServerGui)
        QtCore.QMetaObject.connectSlotsByName(ServerGui)

    def retranslateUi(self, ServerGui):
        _translate = QtCore.QCoreApplication.translate
        ServerGui.setWindowTitle(_translate("ServerGui", "MainWindow"))
        self.statisticLab.setText(_translate("ServerGui", "Статистика"))
        self.serverSettingsLab.setText(_translate("ServerGui", "Настройка сервера"))
        self.ipLab.setText(_translate("ServerGui", "IP"))
        self.portLab.setText(_translate("ServerGui", "Порт"))
        self.clientListLab.setText(_translate("ServerGui", "Список Клиентов"))
        self.btn_quit.setText(_translate("ServerGui", "Выход"))
        self.menuFile.setTitle(_translate("ServerGui", "File"))
        self.actionExit.setText(_translate("ServerGui", "Exit"))

